### ISSUE TITLE
Compatibilty with Waveshare ESP32-S3-Touch-LCD-1.28

### ISSUE THREAD

**Issue by kcarbuncle** [koogar/Tacho-Stats#1]
Hello, i modified the pin assignments to get it working with the Waveshare ESP32-S3-Touch-LCD-1.28 which seems to be somewhat similar to the Seeeduino XIAO ESP32S3 hardware

Link to hardware: https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.28

Boot up/disconnect display and the first screen actually works fine (some info like CPU clocks doesnt show with HSM, but works OHM based wee monitor), but as it switches to the 2nd screen the data isnt displayed correctly anymore which leads to it being unusable.

EDIT: Just out of courtesy and thanks, adding the main stuff i changed to make it work:

TachoStats_V3_1_7_1_SeeedRoundDisplay.ino
Touch pin declaration:
`CST816S touch(6, 7, 13, 5);  // sda, scl, rst(lcd)?, irq`

TFT setup: 
```
#if defined(Seeeduino_XIAO_RP2040) ^ defined(Seeeduino_XIAO_ESP32C3) ^ defined(Seeeduino_XIAO_ESP32S3)

#define TFT_CS     9
#define TFT_DC     8
#define TFT_RST    14

#define TFT_SCLK   10
#define TFT_MOSI   11
#define TFT_MISO   12

Adafruit_GC9A01A tft(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST, TFT_MISO);
#endif
```
Backlight setup:
```
#if defined(Seeeduino_XIAO_RP2040) ^ defined(Seeeduino_XIAO_ESP32C3) ^ defined(Seeeduino_XIAO_ESP32S3)

/* Screen TFT backlight Pin */
int TFT_backlight_PIN = 2;  // slide dip switch slot 2 to (KE) on the back of the Seeed Round display for backlight control
**#endif**
```

Configuration_Settings.h
Serial event fix (13 is the minimum that works for me, YMMV so increase/decrease as necessary.)
`int Serial_eventDelay = 13; //`

**Comment by koogar** [comment]
HI,

"some info like CPU clocks doesnt show with HSM" did you run the program as admin?

"but as it switches to the 2nd screen the data isnt displayed correctly anymore which leads to it being unusable."

Is the touch screen working, all the 1st, 2nd & 3rd do is rotate the screen. 

I just uploaded the code and it works as intended.

The screen rotating routine is in Touch_ESP32S3.ino

case 0: // 1st SCREEN
        Display_GC9A01_Port_R1(); // USB Socket at the rear
        //tft.setRotation(1);// Rotate the display at the start:  0, 1, 2 or 3 = (0, 90, 180 or 270 degrees)

        break;

      case 1: // 2nd SCREEN
        Display_GC9A01_Port_R2();
        //tft.setRotation(0);// Rotate the display at the start:  0, 1, 2 or 3 = (0, 90, 180 or 270 degrees)

        break;

      case 2: // 3rd SCREEN
        Display_GC9A01_Port_R3();
        //tft.setRotation(2);// Rotate the display at the start:  0, 1, 2 or 3 = (0, 90, 180 or 270 degrees)

        break;

      case 3: // 4th SCREEN
        Display_GC9A01_Port_R0();
        //tft.setRotation(3);// Rotate the display at the start:  0, 1, 2 or 3 = (0, 90, 180 or 270 degrees)

**Comment by kcarbuncle** [comment]
Hello;

>"some info like CPU clocks doesnt show with HSM" did you run the program as admin?

Yes on both, but the libre version outputs the CPU clocks and temps for starters:

OHM based/HardwareSerialMonitor:
![IMG_2016](https://github.com/koogar/Tacho-Stats/assets/28801721/b5fbd879-672d-4f77-925e-b4dc63fac646)

Libre-based/WeeHardwareStats:
![IMG_2019](https://github.com/koogar/Tacho-Stats/assets/28801721/014528c4-62c3-4799-ba5d-2f060340f61f)

>Is the touch screen working, all the 1st, 2nd & 3rd do is rotate the screen.

Ahh yeah, the touch does work, and i was mistaken on the screens (was thinking it was the same as gnat stats?)
![IMG_2023](https://github.com/koogar/Tacho-Stats/assets/28801721/e3d70ccd-fb78-4247-b5bf-eaee27b2d7b4)

The boot screen/initialization/disconnect works, but then as the data refreshes it gets weird:
 
![IMG_2014](https://github.com/koogar/Tacho-Stats/assets/28801721/d5b7124e-f74d-442e-b804-0afe842bbd67)

(this is after a few seconds after the correct screens above:)
![IMG_2018](https://github.com/koogar/Tacho-Stats/assets/28801721/a199c946-3c8c-41e0-a75d-af8ed6fc1116)

**Comment by koogar** [comment]
Try altering this by a little in the Configuration to stop corruption of the data. Don't run it through a usb hub

/* Delay screen event, to stop screen data corruption ESP8622 use 25, most others 5 will do*/
int Serial_eventDelay = 5; //

**Comment by kcarbuncle** [comment]
Thanks! Increased the value to 15 and it doesnt have any major issues now (other than the missing hardware info depending on what i use, i think the missing GPU power is down to drivers at this point). I guess i can close this thread now.
